controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Frontend ###
home:
   path: /
   controller: App\Controller\vt

findMovieById:
   path: /findMovieById
   controller: App\Controller\FrontendController::findMovieById

findMovies:
   path: /findMovies
   controller: App\Controller\FrontendController::findMovies

showMovieDetails:
   path: /showMovieDetails/{id}
   controller: App\Controller\FrontendController::showMovieDetails
   defaults:
       id: 1
   requirements:
       id: '[1-9]+[0-9]*'
# Backend ###
homeBackend:
   path: /backend
   controller: App\Controller\vt

movies:
   path: /admin/movies
   controller: App\Controller\Admin\MovieController::index

types:
   path: /admin/types
   controller: App\Controller\BackendController::types

users:
   path: /admin/user
   controller: App\Controller\Admin\ClientController::index

sales:
   path: /admin/sales
   controller:  App\Controller\Admin\CommandController::index


